### ISSUE TITLE
Current install of Dataspeed DBW breaks the project.

### ISSUE THREAD

**Issue by Rob-Crane** [udacity/CarND-Capstone#306] opened 2019-06-26 16:00 UTC
The latest version of Dataspeed DBW changes the message definition of SteeringReport.  The `steering_wheel_angle_cmd` field, which is populated in `bridge.py` no longer exists in the SteeringReport message installed by default.  See the recent commit history:
https://bitbucket.org/DataspeedInc/dbw_mkz_ros/src/b9babb804fc3ffd6e14ba9d12b1df3c3908c121c/dbw_mkz_msgs/msg/SteeringReport.msg?at=default

**Comment by alex4men** [comment] 2019-08-10 00:21
@Rob-Crane Since in the  dbw_mkz library of the latest version 1.2.2 the message SteeringReport has new format (same problem here https://github.com/udacity/CarND-Capstone/pull/296), try to downgrade the dbw_mkz library to the version 1.1.1:
`sudo apt-get install ros-$ROS_DISTRO-dbw-mkz=1.1.1* ros-$ROS_DISTRO-dbw-mkz-msgs=1.1.1* ros-$ROS_DISTRO-dbw-mkz-can=1.1.1* ros-$ROS_DISTRO-dbw-mkz-description=1.1.1* ros-$ROS_DISTRO-dbw-mkz-joystick-demo=1.1.1*`

**Comment by alex4men** [comment] 2019-08-10 00:22
Duplicate of #296

**Comment by UAnjali** [comment] 2021-09-19 15:45
Hi @alex4men,
We are closing out the issue because it has already been addressed in this [PR](https://github.com/udacity/CarND-Capstone/pull/296).

**Closed by UAnjali** 2021-09-19 15:45 UTC
