### ISSUE TITLE
turning on the camera slows car down so auto-mode gets messed up

### ISSUE THREAD

**Issue by rfsch** [udacity/CarND-Capstone#266] opened 2018-11-30 22:58 UTC
turning on the camera slows car down so automode gets messed up
Profile image
Rupert S
about 1 hour ago
Hi

I am able to successfully complete many laps in the sim in automode. car follows green line.

but when i turn on the camera everything slows down such that the communication between ros and the car gets out of sync. for example right at the first stop light the car starts lagging behind the green waypoint line (ie the line sticks out the back of the car).

I suspect that the VM coms to external simulator is too slow ? or the image traffic to large.

I have also traffic lights working and the car slows down when seeing the first red light but cannot stop in time. when it sees green it accelerates

how can i debug this problem ??

thanks

**Comment by mvirgo** [comment] 2018-12-03 19:38
This is a combination of the sim being slow plus ROS being slow. We are looking into using ROS# to hopefully alleviate some of the communication slowness here. We may also need to slow down how quickly images are pulled in.

Are you using a GPU when the slow down occurs or otherwise also using an image classifier? 

For the last one on slowing down for the red but not stopping in time, this sounds like more of a thing to fix within your own code, although if you have any further details there or images that could also be helpful.

**Comment by edupaz2** [comment] 2019-01-07 04:32
I'm having same problem here.

I want to point out that I´m having the same lag always at the same spot, after passing/stopping the first 4 traffic lights (near two cliffs on the left side). At that point I'm not using the classifier (because there are not traffic lights near).

- I'm using GPU to classify traffic lights.
- I'm not classifying when a traffic light is far away.
- The waypoint publisher rate is around 0.01s.

**Comment by papiot** [comment] 2019-01-18 14:05
Having the same problem on the workspace setup to the point that the car goes off track with the camera on every single time in less than 10s. Any idea?

**Comment by OmarBarakat1995** [comment] 2019-02-08 15:46
Same problem here on udacity's workspace.

**Comment by t3pa** [comment] 2019-02-16 18:46
Same problem here on Udacity workspace, even without camera images or traffic light classification.
With the code from the project walkthrough, simulator is so slow that car behavior is totally not reproducible. One time, it will follow the waypoints, another time, it will not at all. I can already tell when I start the Desktop VNC viewer that it is too slow, because the mouse arrow won't move! So how am I supposed to work with the "workspace"...?

**Comment by sm-azure** [comment] 2019-03-31 02:59
I am using a Windows 10 (Xeon E5-1620, 16Gb, GPU) system. Enabling image acquisition from the Sim is messing up the waypoint following. Tried first with ROS in the VM and then on Docker. Same issue. Any ideas other than native Linux install?

**Comment by einrob** [comment] 2019-06-27 19:53
I am stuck on this too. Now running on two machines connected via Ethernet P2P. 

Running natively:
https://www.youtube.com/watch?v=k6-vnAKnMIQ&feature=youtu.be

Running on workspace:
https://www.youtube.com/watch?v=jQiQHUMEivk&feature=youtu.be

Question on Udacity Knowledge without propper solution: 
https://knowledge.udacity.com/questions/48678

I am running Ubuntu natively installed on:
Intel® Core™ i5-2520M CPU @ 2.50GHz × 4
NVidia NVS 4200M/PCIe/SSE2 1GB dedicated

Ran simulation on Windows machine: 
Intel Xeon CPU E3-1505M v5@ 2.80GHz 4 Core HT
NVidia Quadro M2000M 4Gig
64GB RAM 

Still the simulation starts to lagg after a while and car cannot be controlled anymore.

**Comment by SecondProfessionalLife** [comment] 2019-06-30 20:24
Same issue with workspace and VirtualBox on a windows laptop with 8GB and i5 CPU.
Has anyone experience with a native ubuntu installation and gpu support?

**Comment by al-rigazzi** [comment] 2019-07-11 09:46
Hey,

same issue here, on a Mac, using Docker.

To me, it clearly seems like the camera is publishing too many images, which cannot be passed at the needed speed. This results in lag -terrible lag- and the only way to recover is to switch the camera off. I cannot find a way to suspend the camera publisher from the code, which could be enough to let the image be processed before acquiring a new one.

Is there a chance you can turn the camera publishing frequency down (or make it controllable) in the simulator?

**Comment by einrob** [comment] 2019-07-11 13:19
I am still stuck on this problem. Tried following combinations: 

**Variant1:** 
Ubuntu natively installed  running Udacity ROS nodes + Simulation:
Intel® Core™ i5-2520M CPU @ 2.50GHz × 4
NVidia NVS 4200M/PCIe/SSE2 1GB dedicated

**Variant2:** 
Ubuntu natively installed running Udacity ROS Nodes
Intel® Core™ i5-2520M CPU @ 2.50GHz × 4
NVidia NVS 4200M/PCIe/SSE2 1GB dedicated

P2P Connected Windows 10 machine running simulation only
Intel Xeon CPU E3-1505M v5@ 2.80GHz 4 Core HT
NVidia Quadro M2000M 4Gig
64GB RAM

**Variant3:**
Running VirtualBox with Ubuntu Udacity ROS Nodes - Simulation running using Windows 10 (recommended Udacity setup).
Intel Xeon CPU E3-1505M v5@ 2.80GHz 4 Core HT
NVidia Quadro M2000M 4Gig
64GB RAM

All variants show the same symptoms. 

I tried only to run the ROS Nodes communicating with the simulator, still the same issue and no "student code" is involved. 

Started to look into bridge.py and server.py from udacity interfacing the simulator. I think there is no way to reduce the transmission rate of the images without looking into the simulator code. 

I wrote Udacity on 25.06.2019 still no appropriate reply except "request is processed or request is forwarded to the right people".  

There are some older post here. I would really appreciate if anyone could post his or her solution to this problem if they passed the term.

**Comment by ghicheon** [comment] 2019-08-29 00:34
same problem with workspace and VM VirtualBox.
In my case, it's fixed by using Windows 10 ubuntu 16.04 bash. It was not easy procedures to set the environment though.. 

* H/W specs: HP ELITEBOOK /default graphic card/ intel core i7-8550U  / 16G

**Comment by ghicheon** [comment] 2019-09-09 00:59
If very light classification code was implemented, windows 10 bash might be enough. I found a capstone project running well on it.
I found out that native installed ubuntu with GPU is the best option as many people suggested.
It works well on GTX 1070 laptop.

Following article was very helpful for installation.
http://nicholaspropes.com/entries/general/installing-tensorflow-1-3-cuda-toolkit-8-0---cudnn-6-0-on-asus-gl502vs-ds71-laptop-with-ubuntu-16-04-and-nvidia-1070

Like others, I really had a hard time to run this project.  Hopefully, nobody is suffering from it anymore.

**Comment by UAnjali** [comment] 2021-09-23 11:04
Hi everyone,
Closing this issue, as:

- Udacity has applied a performance fix to the project code. The latency should be much less now. There is no programmatic way to turn the camera on or off. See this thread https://knowledge.udacity.com/questions/66433.

**Closed by UAnjali** 2021-09-23 11:04 UTC
