### ISSUE TITLE
Can't see the video and Google's link.

### ISSUE THREAD

**Issue by MikeBMW** [udacity/CarND-Capstone#200] opened 2018-04-06 00:34 UTC
Can't see the video of "Detection walkthrough" and "Full waypoint walkthrough", can't open Google's link.

**Comment by mvirgo** [comment] 2018-04-12 23:51
What is the google link you mention?

Both of the videos appear to be working as intended currently, please let me know if you still cannot see them.

**Comment by mvirgo** [comment] 2018-06-06 21:49
No further comments; closing.

**Closed by mvirgo** 2018-06-06 21:49 UTC
